FROM istio/pilot:1.1.0-snapshot.4

RUN apt-get update && apt-get -q install -y \
    curl

ENTRYPOINT /usr/local/bin/pilot-discovery  discovery \
  --registries=Mock \
  --meshConfig=/dev/null \
  --plugins=health \
  --httpAddr=:8000 \
  --grpcAddr=:15010 \
  --mcpServerAddrs=mcp://host.docker.internal:18000




