FROM istio/pilot:1.0.2

RUN apt-get update && apt-get -q install -y \
    curl

ENTRYPOINT /usr/local/bin/pilot-discovery  discovery \
  --configDir=/etc/istio-config \
  --registries=Mock \
  --meshConfig=/dev/null \
  --plugins=health \
  --httpAddr=:8000 \
  --grpcAddr=:15010




