FROM istio/pilot:1.1.0-snapshot.6

RUN apt-get update && apt-get -q install -y \
    curl

ENTRYPOINT /usr/local/bin/pilot-discovery  discovery \
  --registries=Mock \
  --meshConfig=/dev/null \
  --plugins=health \
  --httpAddr=:8000 \
  --grpcAddr=:15010 \
  --meshConfig=/etc/mesh-config.yaml \
  --secureGrpcAddr=




