


[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.1"

[[constraint]]
  name = "istio.io/api"
  branch = "release-1.1"

[[constraint]]
  name = "istio.io/istio"
  branch = "release-1.1"

[prune]
  go-tests = true
  unused-packages = true
